function q_ddot_symvar = SinglePendulumCart_auto(I2,c2,g,g1_1,g1_2,g1_3,g1_4,g1_5,g1_6,g2_1,g2_2,g2_3,g2_4,g2_5,g2_6,m1,m2,q1_dot,q2,q2_dot,u)
%SINGLEPENDULUMCART_AUTO
%    Q_DDOT_SYMVAR = SINGLEPENDULUMCART_AUTO(I2,C2,G,G1_1,G1_2,G1_3,G1_4,G1_5,G1_6,G2_1,G2_2,G2_3,G2_4,G2_5,G2_6,M1,M2,Q1_DOT,Q2,Q2_DOT,U)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    25-Feb-2020 17:04:11

t2 = c2.^2;
t3 = m2.^2;
t4 = cos(q2);
t5 = g1_5.*q1_dot;
t6 = tanh(t5);
t7 = g1_3.*q1_dot;
t8 = tanh(t7);
t22 = g1_2.*q1_dot;
t9 = t8-t22;
t10 = tanh(t9);
t11 = q2.*2.0;
t12 = sin(t11);
t13 = q2_dot.^2;
t14 = sin(q2);
t15 = I2.*m1;
t16 = I2.*m2;
t17 = t2.*t3;
t18 = t4.^2;
t19 = m1.*m2.*t2;
t20 = t15+t16+t17+t19-t2.*t3.*t18;
t21 = 1.0./t20;
t23 = g2_5.*q2_dot;
t24 = tanh(t23);
t25 = g2_3.*q2_dot;
t26 = tanh(t25);
t29 = g2_2.*q2_dot;
t27 = t26-t29;
t28 = tanh(t27);
q_ddot_symvar = [t21.*(I2.*u.*2.0-I2.*g1_6.*q1_dot.*2.0-I2.*g1_4.*t6.*2.0+I2.*g1_1.*t10.*2.0+m2.*t2.*u.*2.0-g1_6.*m2.*q1_dot.*t2.*2.0-g1_4.*m2.*t2.*t6.*2.0+g1_1.*m2.*t2.*t10.*2.0+g.*t2.*t3.*t12+I2.*c2.*m2.*t13.*t14.*2.0+c2.*g2_6.*m2.*q2_dot.*t4.*2.0+c2.*g2_4.*m2.*t4.*t24.*2.0-c2.*g2_1.*m2.*t4.*t28.*2.0+c2.*t2.*t3.*t13.*t14.*2.0-q1_dot.*q2_dot.*t2.*t3.*t12).*(1.0./2.0);-t21.*(t14.*(c2.*m2.*(g.*m1+g.*m2-m1.*q1_dot.*q2_dot-m2.*q1_dot.*q2_dot)+t2.*t3.*t4.*t13)+t4.*(c2.*m2.*u-c2.*g1_6.*m2.*q1_dot-c2.*g1_4.*m2.*t6+c2.*g1_1.*m2.*t10)+g2_6.*m1.*q2_dot+g2_6.*m2.*q2_dot+g2_4.*m1.*t24-g2_1.*m1.*t28+g2_4.*m2.*t24-g2_1.*m2.*t28)];
