function q_ddot_symvar = SinglePendulumCart_auto(I2,c2,g,g1_1,g1_2,g1_3,g1_4,g1_5,g1_6,g2_1,g2_2,g2_3,g2_4,g2_5,g2_6,m1,m2,q1_dot,q2,q2_dot,u)
%SINGLEPENDULUMCART_AUTO
%    Q_DDOT_SYMVAR = SINGLEPENDULUMCART_AUTO(I2,C2,G,G1_1,G1_2,G1_3,G1_4,G1_5,G1_6,G2_1,G2_2,G2_3,G2_4,G2_5,G2_6,M1,M2,Q1_DOT,Q2,Q2_DOT,U)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    27-Oct-2020 22:05:09

t2 = c2.^2;
t3 = m2.^2;
t4 = cos(q2);
t5 = g1_5.*q1_dot;
t6 = tanh(t5);
t7 = g1_3.*q1_dot;
t8 = tanh(t7);
t27 = g1_2.*q1_dot;
t9 = t8-t27;
t10 = tanh(t9);
t11 = q2_dot.^2;
t12 = I2.*m1;
t13 = I2.*m2;
t14 = t2.*t3;
t15 = t4.^2;
t16 = m1.*m2.*t2;
t17 = t12+t13+t14+t16-t2.*t3.*t15;
t18 = 1.0./t17;
t19 = g2_5.*q2_dot;
t20 = tanh(t19);
t21 = g2_3.*q2_dot;
t22 = tanh(t21);
t25 = g2_2.*q2_dot;
t23 = t22-t25;
t24 = tanh(t23);
t26 = sin(q2);
q_ddot_symvar = [t18.*(I2.*u-I2.*g1_6.*q1_dot-I2.*g1_4.*t6+I2.*g1_1.*t10+m2.*t2.*u-g1_6.*m2.*q1_dot.*t2-g1_4.*m2.*t2.*t6+g1_1.*m2.*t2.*t10+c2.*m2.*t26.*(I2.*t11+m2.*t2.*t11+c2.*g.*m2.*t4)+c2.*g2_6.*m2.*q2_dot.*t4+c2.*g2_4.*m2.*t4.*t20-c2.*g2_1.*m2.*t4.*t24);-t18.*(g2_6.*m1.*q2_dot+g2_6.*m2.*q2_dot+g2_4.*m1.*t20-g2_1.*m1.*t24+g2_4.*m2.*t20-g2_1.*m2.*t24+c2.*m2.*t4.*u+c2.*m2.*t26.*(g.*m1+g.*m2+c2.*m2.*t4.*t11)-c2.*g1_6.*m2.*q1_dot.*t4-c2.*g1_4.*m2.*t4.*t6+c2.*g1_1.*m2.*t4.*t10)];
