function q_ddot_symvar = SinglePendulumCart_auto(I2,b1,b2,c2,g,m1,m2,q1_dot,q2,q2_dot,u)
%SINGLEPENDULUMCART_AUTO
%    Q_DDOT_SYMVAR = SINGLEPENDULUMCART_AUTO(I2,B1,B2,C2,G,M1,M2,Q1_DOT,Q2,Q2_DOT,U)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    29-Oct-2019 21:27:59

t2 = sin(q2);
t3 = c2.^2;
t4 = cos(q2);
t5 = m2.^2;
t6 = q2_dot.^2;
t7 = I2.*m1;
t8 = I2.*m2;
t9 = m1.*m2.*t3;
q_ddot_symvar = [(I2.*u+t2.*(c2.*m2.*t6.*(I2+m2.*t3)+c2.*m2.*t4.*(c2.*g.*m2-c2.*m2.*q1_dot.*q2_dot))-I2.*b1.*q1_dot+m2.*t3.*u-b1.*m2.*q1_dot.*t3+b2.*c2.*m2.*q2_dot.*t4)./(t7+t8+t9+t2.^2.*t3.*t5);-(t4.*(c2.*m2.*u-b1.*c2.*m2.*q1_dot+t2.*t3.*t5.*t6)+t2.*(c2.*g.*t5+c2.*g.*m1.*m2-c2.*q1_dot.*q2_dot.*t5-c2.*m1.*m2.*q1_dot.*q2_dot)+b2.*m1.*q2_dot+b2.*m2.*q2_dot)./(t7+t8+t9+t3.*t5-t3.*t4.^2.*t5)];
