function q_ddot_symvar = SinglePendulumCart_auto(I2,b2,c2,g,m1,m2,q2,q2_dot,u)
%SINGLEPENDULUMCART_AUTO
%    Q_DDOT_SYMVAR = SINGLEPENDULUMCART_AUTO(I2,B2,C2,G,M1,M2,Q2,Q2_DOT,U)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    27-Oct-2020 21:39:35

t2 = cos(q2);
t3 = c2.^2;
t4 = m2.^2;
t5 = q2_dot.^2;
t6 = sin(q2);
t7 = I2.*m1;
t8 = I2.*m2;
t9 = m1.*m2.*t3;
q_ddot_symvar = [(I2.*u+t6.*(c2.*t3.*t4.*t5+I2.*c2.*m2.*t5)+t2.*(b2.*c2.*m2.*q2_dot+g.*t3.*t4.*t6)+m2.*t3.*u)./(t7+t8+t9-t3.*t4.*(t2.^2-1.0));-(t6.*(c2.*g.*t4+c2.*g.*m1.*m2+t2.*t3.*t4.*t5)+b2.*m1.*q2_dot+b2.*m2.*q2_dot+c2.*m2.*t2.*u)./(t7+t8+t9+t3.*t4.*t6.^2)];
