function q_ddot_symvar = Cart_auto(b,q1_dot,u)
%CART_AUTO
%    Q_DDOT_SYMVAR = CART_AUTO(B,Q1_DOT,U)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    01-Nov-2019 12:40:04

q_ddot_symvar = -q1_dot+u./b;
