function q_ddot_symvar = Cart_auto(b,m,q1_dot,u)
%CART_AUTO
%    Q_DDOT_SYMVAR = CART_AUTO(B,M,Q1_DOT,U)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    12-Jan-2020 14:48:54

q_ddot_symvar = (u-b.*q1_dot)./m;
